### ISSUE TITLE
Training without pretrained checkpoint

### ISSUE THREAD

**Issue by elstonartc** [YuHengsss/YOLOV#104]
Hello! I have successfully reproduced the code and repository. I also managed to format my own dataset and train with it and have managed to see losses go down, however right the AP for one of my classes are always nan and the AP is always 0.

How do I also train without having to include `-c ./V++_FocalL.pth` in the training command? I think the problem may be because the pretrained num_classes and my num_classes are not the same. The traceback is down below for when I do not include pretrained weights.

```
2024-10-21 10:33:54 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (22828), thread 'MainThread' (14464):
Traceback (most recent call last):

  File "tools\vid_train.py", line 138, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, cache=False, ckpt='', devices=1, dist_backend='nccl', dist_url=None, exp_file='./exps/yolov++/vplusF...
          └ ╒════════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "c:\users\desktop\downloads\elston\yolov\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒════════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000002E5CB759950>

  File "tools\vid_train.py", line 115, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000002E5CB759158>
    └ <yolox.core.vid_trainer.Trainer object at 0x000002E5CB751F28>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\vid_trainer.py", line 120, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x000002E5CB759378>
    └ <yolox.core.vid_trainer.Trainer object at 0x000002E5CB751F28>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\vid_trainer.py", line 192, in before_train
    model = self.resume_train(model)
            │    │            └ YOLOV(
            │    │                (backbone): YOLOPAFPN_focal(
            │    │                  (backbone): FocalNet(
            │    │                    (patch_embed): PatchEmbed(
            │    │                      (proj): Conv2d(3, 19...
            │    └ <function Trainer.resume_train at 0x000002E5CB759730>
            └ <yolox.core.vid_trainer.Trainer object at 0x000002E5CB751F28>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\vid_trainer.py", line 360, in resume_train
    ckpt = torch.load(ckpt_file, map_location=self.device)["model"]
           │     │    │                       │    └ 'cuda:0'
           │     │    │                       └ <yolox.core.vid_trainer.Trainer object at 0x000002E5CB751F28>
           │     │    └ ''
           │     └ <function load at 0x000002E590F86F28>
           └ <module 'torch' from 'C:\\Users\\Desktop\\anaconda3\\envs\\yolov\\lib\\site-packages\\torch\\__init__.py'>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
         │               └ ''
         └ <function _open_file_like at 0x000002E590F86400>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
           │          │               └ 'rb'
           │          └ ''
           └ <class 'torch.serialization._open_file'>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
          │           │                   │     └ 'rb'
          │           │                   └ ''
          │           └ <torch.serialization._open_file object at 0x000002E6448BDF98>
          └ <class 'torch.serialization._open_file'>

FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by elstonartc** [comment]
Fixed, the issue is default value of -ckpt or -c flag is False and not None so even if no checkpoint is put in, it will still run loading a checkpoint
Old code (line 357 vid_trainer.py):
```
if self.args.ckpt is not None:
        logger.info("loading checkpoint for fine tuning")
        ckpt_file = self.args.ckpt
        ckpt = torch.load(ckpt_file, map_location=self.device)["model"]
        model = load_ckpt(model, ckpt)
    self.start_epoch = 0
```
New code:
```
if self.args.ckpt:
        logger.info("loading checkpoint for fine tuning")
        ckpt_file = self.args.ckpt
        ckpt = torch.load(ckpt_file, map_location=self.device)["model"]
        model = load_ckpt(model, ckpt)
    self.start_epoch = 0
```
