### ISSUE TITLE
Problem with Training Base Detector

### ISSUE THREAD

**Issue by Elstuhn** [YuHengsss/YOLOV#105]
```
import os
import torch
import torch.nn as nn
from yolox.exp import Exp as MyExp
from loguru import logger


class Exp(MyExp):
    def __init__(self):
        super(Exp, self).__init__()
        self.data_dir = './datasets/videopipe-labelled/'
        self.train_ann = "train_annotations.json"
        # name of annotation file for evaluation
        self.val_ann = "val_annotations.json"
        self.train_name = 'images/train'
        self.val_name = 'images/val'
        self.basic_lr_per_img = 0.0001 / 64.0
        self.save_history_ckpt = True
        self.max_epoch = 100
        self.input_size = (576,576)
        self.test_size = (576,576)
        self.eval_interval = 10
        self.warmup_epochs = 0
        self.no_aug_epochs = 100
        self.num_classes = 4
        self.test_conf = 0.001
        self.scheduler = 'warmcos'
        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]
        self.focal_level = 4
        self.focal_windows = 3
        self.debug = True

    def get_model(self):
        def init_yolo(M):
            for m in M.modules():
                if isinstance(m, nn.BatchNorm2d):
                    m.eps = 1e-3
                    m.momentum = 0.03

        in_channels = [96 * 4, 96 * 8, 96 * 16]
        out_channels = in_channels #[96 * 2, 96 * 4, 96 * 4, 96 * 8] #in_channels #[256, 512, 1024]
        from yolox.models import YOLOX, YOLOPAFPN_focal, YOLOXHead
        backbone = YOLOPAFPN_focal(in_channels=in_channels,  
                                  out_channels=out_channels,
                                  act=self.act,
                                  in_features=(1, 2, 3),
                                  depths=[2, 2, 18, 2],
                                  focal_levels = [4, 4, 4, 4],
                                  focal_windows = [3, 3, 3, 3],
                                  use_conv_embed = True, 
                                  use_postln = True,
                                  use_postln_in_modulation = False,
                                  use_layerscale = True,
                                  base_dim=192#int(in_channels[0])
                                  )
        head = YOLOXHead(self.num_classes, self.width,
                         in_channels=[96 * 4, 96 * 8, 96 * 16],
                         act=self.act, strides=[8, 16, 32],debug=self.debug)

        # for layer in backbone.backbone.parameters():
        #     layer.requires_grad = False  # fix the backbone
        def fix_bn(m):
            classname = m.__class__.__name__
            if classname.find('BatchNorm') != -1:
                m.eval()
        self.model = YOLOX(backbone, head)

        self.model.apply(init_yolo)
        self.model.head.initialize_biases(1e-2)

        return self.model

    def get_optimizer(self, batch_size):
        if "optimizer" not in self.__dict__:
            if self.warmup_epochs > 0:
                lr = self.warmup_lr
            else:
                lr = self.basic_lr_per_img * batch_size

            pg0, pg1, pg2, pg3, pg4 = [], [], [], [], []  # optimizer parameter groups

            for k, v in self.model.named_modules():
                if hasattr(v, "bias") and isinstance(v.bias, nn.Parameter):
                    pg2.append(v.bias)  # biases
                if isinstance(v, nn.BatchNorm2d) or "bn" in k:
                    pg0.append(v.weight)  # no decay
                elif hasattr(v, 'absolute_pos_embed') or hasattr(v, 'relative_position_bias_table') or hasattr(v,
                                                                                                               'norm'):
                    if hasattr(v, 'weight'):
                        pg3.append(v.weight)
                elif hasattr(v, "weight") and isinstance(v.weight, nn.Parameter):
                    if "backbone.backbone" in k:  # check if it is the backbone
                        logger.info("backbone weight: {}".format(k))
                        pg4.append(v.weight)
                    else:
                        pg1.append(v.weight)  # apply decay

            optimizer = torch.optim.AdamW(params=pg0, lr=lr, weight_decay=self.weight_decay)
            optimizer.add_param_group(
                {"params": pg1, "weight_decay": self.weight_decay}
            )  # add pg1 with weight_decay
            optimizer.add_param_group(
                {"params": pg3, "weight_decay": 0}
            )  # add pg1 with weight_decay
            optimizer.add_param_group({"params": pg2})
            optimizer.add_param_group({"params": pg4, "weight_decay": self.weight_decay})


            self.optimizer = optimizer

        return self.optimizer
```

```
2024-10-24 09:22:49 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (2292), thread 'MainThread' (59276):
Traceback (most recent call last):

  File "tools\train.py", line 140, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=2, cache=False, ckpt=None, devices=1, dist_backend='nccl', dist_url=None, exp_file='./exps/swin_base/foc...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "c:\users\desktop\downloads\elston\yolov-clone\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000002CC8ECBDAE8>

  File "tools\train.py", line 117, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000002CC8FC62378>
    └ <yolox.core.trainer.Trainer object at 0x000002CC8FC522B0>

  File "c:\users\desktop\downloads\elston\yolov-clone\yolox\core\trainer.py", line 76, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x000002CC8FC629D8>
    └ <yolox.core.trainer.Trainer object at 0x000002CC8FC522B0>

  File "c:\users\desktop\downloads\elston\yolov-clone\yolox\core\trainer.py", line 86, in train_in_epoch
    self.after_epoch()
    │    └ <function Trainer.after_epoch at 0x000002CC8FC62D08>
    └ <yolox.core.trainer.Trainer object at 0x000002CC8FC522B0>

  File "c:\users\desktop\downloads\elston\yolov-clone\yolox\core\trainer.py", line 221, in after_epoch
    self.evaluate_and_save_model()
    │    └ <function Trainer.evaluate_and_save_model at 0x000002CC8FC50048>
    └ <yolox.core.trainer.Trainer object at 0x000002CC8FC522B0>

  File "c:\users\desktop\downloads\elston\yolov-clone\yolox\core\trainer.py", line 325, in evaluate_and_save_model
    evalmodel, self.evaluator, self.is_distributed
    │          │    │          │    └ False
    │          │    │          └ <yolox.core.trainer.Trainer object at 0x000002CC8FC522B0>
    │          │    └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x000002CC9C746DA0>
    │          └ <yolox.core.trainer.Trainer object at 0x000002CC8FC522B0>
    └ YOLOX(
        (backbone): YOLOPAFPN_focal(
          (backbone): FocalNet(
            (patch_embed): PatchEmbed(
              (proj): Conv2d(3, 19...

  File "c:\users\desktop\downloads\elston\yolov-clone\yolox\exp\yolox_base.py", line 330, in eval
    return evaluator.evaluate(model, is_distributed, half)
           │         │        │      │               └ False
           │         │        │      └ False
           │         │        └ YOLOX(
           │         │            (backbone): YOLOPAFPN_focal(
           │         │              (backbone): FocalNet(
           │         │                (patch_embed): PatchEmbed(
           │         │                  (proj): Conv2d(3, 19...
           │         └ <function COCOEvaluator.evaluate at 0x000002CC8FB7BD08>
           └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x000002CC9C746DA0>

  File "c:\users\desktop\downloads\elston\yolov-clone\yolox\evaluators\coco_evaluator.py", line 184, in evaluate
    outputs, self.num_classes, self.confthre, self.nmsthre
    │        │    │            │    │         │    └ 0.65
    │        │    │            │    │         └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x000002CC9C746DA0>
    │        │    │            │    └ 0.001
    │        │    │            └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x000002CC9C746DA0>
    │        │    └ 4
    │        └ <yolox.evaluators.coco_evaluator.COCOEvaluator object at 0x000002CC9C746DA0>
    └ ([tensor([[ 1.9156e+02,  2.1721e+02,  6.7064e+02,  3.0481e+02,  1.4476e-01,
                6.1006e-01,  2.0000e+00],
              [-6.8...

  File "c:\users\desktop\downloads\elston\yolov-clone\yolox\utils\boxes.py", line 33, in postprocess
    box_corner = prediction.new(prediction.shape)
                 │              └ ([tensor([[ 1.9156e+02,  2.1721e+02,  6.7064e+02,  3.0481e+02,  1.4476e-01,
                 │                          6.1006e-01,  2.0000e+00],
                 │                        [-6.8...
                 └ ([tensor([[ 1.9156e+02,  2.1721e+02,  6.7064e+02,  3.0481e+02,  1.4476e-01,
                             6.1006e-01,  2.0000e+00],
                           [-6.8...

AttributeError: 'tuple' object has no attribute 'new'
```

The above is my Exp file for /exps/swin_base/focal_large_base_vid.py and the error I get when I try to train it using `python tools/train.py -f ./exps/swin_base/focal_large_base_vid.py -b 2`. The annotation files I have provided are in accordance with COCO annotation format just like YOLOV/annotations/vid_train_coco.json and YOLOV/annotations/ILSVRC_FGFA_COCO.json. 
Please advise how I may fix this issue and move forward from here, thank you!

**Comment by YuHengsss** [comment]
Please just set the debug flag to false: https://github.com/YuHengsss/YOLOV/blob/98ade28ce975291023be947b7d5d57b05f9600ba/exps/swin_base/focal_large_base_vid.py#L31 .

Additionally, when training on your own dataset, it is recommended to use COCO pretrained weights for initialization to avoid poor performance. Since the pretrained backbone for FocalNet-Large on the COCO dataset is not available for now, you might consider using either Swin-Base or Swin-Tiny as alternatives.

**Comment by Elstuhn** [comment]
Thank you so much for your guidance, it works now! However some unexpected bugs have came up, I have set max_epochs to 200 in both main Exp file and BaseExp file but seems that training is unexpectedly cut off after just 1 or 2 epochs is there a way to fix it or the only way for now is to keep on resuming training?

**Comment by YuHengsss** [comment]
Just give it a try and look forward to your feedback.

**Comment by Elstuhn** [comment]
```
2024-10-24 18:01:37 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (94668), thread 'MainThread' (24372):
Traceback (most recent call last):

  File "tools\train.py", line 140, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=3, cache=False, ckpt=None, devices=1, dist_backend='nccl', dist_url=None, exp_file='./exps/swin_base/foc...
          └ ╒═══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "c:\users\desktop\downloads\elston\yolov\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒═══════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x000002844CD18EA0>

  File "tools\train.py", line 117, in main
    trainer.train()
    │       └ <function Trainer.train at 0x000002844DBC6F28>
    └ <yolox.core.trainer.Trainer object at 0x000002844DBD8438>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\trainer.py", line 76, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x000002844DBCF730>
    └ <yolox.core.trainer.Trainer object at 0x000002844DBD8438>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\trainer.py", line 85, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x000002844DBCF7B8>
    └ <yolox.core.trainer.Trainer object at 0x000002844DBD8438>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\trainer.py", line 91, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x000002844DBCF840>
    └ <yolox.core.trainer.Trainer object at 0x000002844DBD8438>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\trainer.py", line 111, in train_one_iter
    self.scaler.step(self.optimizer)
    │    │      │    │    └ AdamW (
    │    │      │    │      Parameter Group 0
    │    │      │    │          amsgrad: False
    │    │      │    │          betas: (0.9, 0.999)
    │    │      │    │          capturable: False
    │    │      │    │          eps: 1e-08
    │    │      │    │          foreach: None
    │    │      │    │       ...
    │    │      │    └ <yolox.core.trainer.Trainer object at 0x000002844DBD8438>
    │    │      └ <function GradScaler.step at 0x0000028442D39E18>
    │    └ <torch.cuda.amp.grad_scaler.GradScaler object at 0x000002844DBD84E0>
    └ <yolox.core.trainer.Trainer object at 0x000002844DBD8438>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
             │    │               │          │                 │       └ {}
             │    │               │          │                 └ ()
             │    │               │          └ {'stage': <OptState.UNSCALED: 1>, 'found_inf_per_device': {device(type='cuda', index=0): tensor([0.], device='cuda:0')}}
             │    │               └ AdamW (
             │    │                 Parameter Group 0
             │    │                     amsgrad: False
             │    │                     betas: (0.9, 0.999)
             │    │                     capturable: False
             │    │                     eps: 1e-08
             │    │                     foreach: None
             │    │                  ...
             │    └ <function GradScaler._maybe_opt_step at 0x0000028442D39D90>
             └ <torch.cuda.amp.grad_scaler.GradScaler object at 0x000002844DBD84E0>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
             │         │     │       └ {}
             │         │     └ ()
             │         └ <function AdamW.step at 0x00000284C2305EA0>
             └ AdamW (
               Parameter Group 0
                   amsgrad: False
                   betas: (0.9, 0.999)
                   capturable: False
                   eps: 1e-08
                   foreach: None
                ...

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\optim\optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (AdamW (
           │       Parameter Group 0
           │           amsgrad: False
           │           betas: (0.9, 0.999)
           │           capturable: False
           │           eps: 1e-08
           │           foreach: None
           │       ...
           └ <function AdamW.step at 0x00000284431E66A8>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (AdamW (
           │       Parameter Group 0
           │           amsgrad: False
           │           betas: (0.9, 0.999)
           │           capturable: False
           │           eps: 1e-08
           │           foreach: None
           │       ...
           └ <function AdamW.step at 0x00000284431E6620>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\optim\adamw.py", line 175, in step
    capturable=group['capturable'])
               └ {'lr': 4.494699424978306e-06, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0.0005, 'amsgrad': False, 'foreach': None,...

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\optim\adamw.py", line 231, in adamw
    capturable=capturable)
               └ False

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\optim\adamw.py", line 259, in _single_tensor_adamw
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
               │      └ <attribute 'is_cuda' of 'torch._C._TensorBase' objects>
               └ tensor(50021., device='cuda:0')

AssertionError: If capturable=False, state_steps should not be CUDA tensors.
```
Alright, will let you know how it goes. Also sorry to bother again but I have ran into another bug. The training sequence, even though I set max_epochs=200 for both the main Exp file and the Base Exp file, will suddenly stop. And when I try to resume training from last checkpoint I get the above error. Please advise once more!

**Comment by YuHengsss** [comment]
It seems this bug comes from yolox code base and I haven't met this bug when I train the base detector on ubuntu system. You may find solution in issues of YOLOX repo or give it a try on ubuntu system.

**Comment by Elstuhn** [comment]
Yep just fixed the resume error, I just changed the Adamw optimizer to be `capturable=True` and resuming works now. Thank you so much for your help and guidance!

**Comment by Elstuhn** [comment]
Yep just fixed the resume error, I just changed the Adamw optimizer to be `capturable=True` and resuming works now. Thank you so much for your help and guidance!
