### ISSUE TITLE
question about evaluation process

### ISSUE THREAD

**Issue by crimson151** [YuHengsss/YOLOV#108]
thanks for your work! 
 following the step in "Reproduce our result on VID",I have trained yolov_s model and ran `python tools/vid_train.py -f exps/yolov/yolov_s.py -c weights/yoloxs_vid.pth --fp16`

 but when i do the Rvaluation process, 
 i use the command:
` python tools/REPPM.py --repp_cfg ./tools/yolo_repp_cfg.json --predictions_file ./yolov_s.pkl --evaluate --annotations_filename ./annotations/annotations_val_ILSVRC.txt --path_dataset ./datasets/VID/ILSVRC2015 --store_imdb --store_coco --post`
 
 and the output as follows:
 
```
 * Loading REPP cfg
{'min_tubelet_score': 0.001, 'add_unmatched': False, 'distance_func': 'logreg', 'clf_thr': 0.7, 'clf_mode': 'dot', 'recoordinate': True, 'recoordinate_std': 0.4, 'min_pred_score': 0.001, 'appearance_matching': False, 'weight_path': './tools/matching_model_logreg.pckl'}
True *******************
Loading clf matching model: ./matching_model_logreg.pckl
/home/pyr/.conda/envs/env1/lib/python3.8/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 0.22 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
ImageSet already computed: ./annotations/annotations_val_ILSVRC_image_set.txt
 * Applying repp
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 555/555 [19:42<00:00,  2.13s/it]
 * Dumping predictions with the IMDB format: ./yolov_s_repp_imdb.txt
 * Dumping predictions with the COCO format: ./yolov_s_repp_coco.json
 * Evaluating REPP predictions
ImageSet already computed: ./annotations/annotations_val_ILSVRC_image_set.txt
Motion File already computed: ./annotations/annotations_val_ILSVRC_motion_iou.mat
Calculating mAP by motion speed
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 176126/176126 [01:35<00:00, 1842.45it/s]
Traceback (most recent call last):
  File "tools/REPPM.py", line 424, in <module>
    stats = get_motion_mAP(args.annotations_filename, args.path_dataset,
  File "/media/pyr/pyr/YOLOV/tools/imagenet_vid_eval_motion.py", line 51, in get_motion_mAP
    ap_data = vid_eval_motion(multifiles, preds_filename_imdb, annopath, imageset_dest_filename, classname_map,
  File "/media/pyr/pyr/YOLOV/tools/imagenet_vid_eval_motion.py", line 233, in vid_eval_motion
    motion_iou = np.array([[motion_iou['motion_iou'][i][0][j][0] if len(motion_iou['motion_iou'][i][0][j]) != 0 else 0 \
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (176126,) + inhomogeneous part.
```

could you give some suggestion on how to solve this problem? thx again and hope for your answering!

**Comment by wr0124** [comment]
same here !
