### ISSUE TITLE
AttributeError: 'Exp' object has no attribute 'pre_no_aug' 

### ISSUE THREAD

**Issue by leilanfang** [YuHengsss/YOLOV#109]
2024-11-05 09:04:41 | INFO     | yolox.core.vid_trainer:240 - ---> start train epoch1
2024-11-05 09:04:41 | INFO     | yolox.core.vid_trainer:235 - Training of experiment is done and the best AP is 0.00
2024-11-05 09:04:41 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (12747), thread 'MainThread' (140682571986752):
Traceback (most recent call last):

  File "tools/vid_train.py", line 131, in <module>
    launch(
    └ <function launch at 0x7ff2bfac99d0>

> File "/22085400415/leilanfang/smoke_fusion_theraml/YOLOV-master/yolox/core/launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒════════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7ff2b69a0ca0>

  File "tools/vid_train.py", line 115, in main
    trainer.train()
    │       └ <function Trainer.train at 0x7ff2b69a0430>
    └ <yolox.core.vid_trainer.Trainer object at 0x7ff2b6998a30>

  File "/22085400415/leilanfang/smoke_fusion_theraml/YOLOV-master/yolox/core/vid_trainer.py", line 122, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x7ff2b69a04c0>
    └ <yolox.core.vid_trainer.Trainer object at 0x7ff2b6998a30>

  File "/22085400415/leilanfang/smoke_fusion_theraml/YOLOV-master/yolox/core/vid_trainer.py", line 130, in train_in_epoch
    self.before_epoch()
    │    └ <function Trainer.before_epoch at 0x7ff2b69a0790>
    └ <yolox.core.vid_trainer.Trainer object at 0x7ff2b6998a30>

  File "/22085400415/leilanfang/smoke_fusion_theraml/YOLOV-master/yolox/core/vid_trainer.py", line 262, in before_epoch
    elif 0< self.epoch + 1 <= self.exp.pre_no_aug + self.exp.warmup_epochs:
            │    │            │    │                │    │   └ 0
            │    │            │    │                │    └ ╒════════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
            │    │            │    │                └ <yolox.core.vid_trainer.Trainer object at 0x7ff2b6998a30>
            │    │            │    └ ╒════════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
            │    │            └ <yolox.core.vid_trainer.Trainer object at 0x7ff2b6998a30>
            │    └ 0
            └ <yolox.core.vid_trainer.Trainer object at 0x7ff2b6998a30>

AttributeError: 'Exp' object has no attribute 'pre_no_aug'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop

**Comment by crimson151** [comment]
i had the same problem when i was training yolov_s.
i change the file "exps/yolov/yolov_s.py" and add code line  `self.pre_no_aug = 0` and it works. 
hope my method works for you too

**Comment by leilanfang** [comment]
I have solved this problem. Can you add my contact information?

**Comment by crimson151** [comment]
> > i had the same problem when i was training yolov_s. i change the file "exps/yolov/yolov_s.py" and add code line `self.pre_no_aug = 0` and it works. hope my method works for you too
> 
> I have solved this problem. Can you add my contact information?

ok  XD
