### ISSUE TITLE
Changing YOLOX Base Detector

### ISSUE THREAD

**Issue by Elstuhn** [YuHengsss/YOLOV#124]
```
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Loss.cu:129: block: [7,0,0], thread: [122,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Loss.cu:129: block: [7,0,0], thread: [123,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Loss.cu:129: block: [7,0,0], thread: [124,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Loss.cu:129: block: [7,0,0], thread: [125,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Loss.cu:129: block: [7,0,0], thread: [126,0,0] Assertion `input_val >= zero && input_val <= one` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\Loss.cu:129: block: [7,0,0], thread: [127,0,0] Assertion `input_val >= zero && input_val <= one` failed.
CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
2024-12-18 17:29:54 | ERROR    | yolox.models.rtmdetHead:608 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.
2024-12-18 17:29:54 | INFO     | yolox.core.vid_trainer:232 - Training of experiment is done and the best AP is 0.00
2024-12-18 17:29:54 | ERROR    | yolox.core.launch:98 - An error has been caught in function 'launch', process 'MainProcess' (22620), thread 'MainThread' (35240):
Traceback (most recent call last):

  File "c:\users\desktop\downloads\elston\yolov\yolox\models\rtmdetHead.py", line 601, in get_losses
    imgs,
    └ <unprintable Tensor object>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ <unprintable tuple object>
           └ <function RTMDetHead.get_assignments at 0x0000021BAE4148C8>

  File "c:\users\desktop\downloads\elston\yolov\yolox\models\rtmdetHead.py", line 840, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
        │    │                  │     │               │           │       └ <unprintable Tensor object>
        │    │                  │     │               │           └ 3
        │    │                  │     │               └ <unprintable Tensor object>
        │    │                  │     └ <unprintable Tensor object>
        │    │                  └ <unprintable Tensor object>
        │    └ <function RTMDetHead.dynamic_k_matching at 0x0000021BAE414A60>
        └ RTMDetHead(
            (cls_convs): ModuleList(
              (0): Sequential(
                (0): BaseConv(
                  (conv): Conv2d(320, 320, kernel_size...

  File "c:\users\desktop\downloads\elston\yolov\yolox\models\rtmdetHead.py", line 953, in dynamic_k_matching
    cost[gt_idx], k=dynamic_ks[gt_idx].item(), largest=False
    │    │          │          └ 0
    │    │          └ <unprintable Tensor object>
    │    └ 0
    └ <unprintable Tensor object>

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "tools\vid_train.py", line 138, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=2, cache=False, ckpt='./rtmdet_epoch68.pth', devices=1, dist_backend='nccl', dist_url=None, exp_file='./...
          └ ╒════════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "c:\users\desktop\downloads\elston\yolov\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒════════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x0000021BF6CDB048>

  File "tools\vid_train.py", line 115, in main
    trainer.train()
    │       └ <function Trainer.train at 0x0000021BF6CD87B8>
    └ <yolox.core.vid_trainer.Trainer object at 0x0000021BECA84080>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\vid_trainer.py", line 116, in train
    self.train_in_epoch()
    │    └ <function Trainer.train_in_epoch at 0x0000021BF6CD8840>
    └ <yolox.core.vid_trainer.Trainer object at 0x0000021BECA84080>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\vid_trainer.py", line 125, in train_in_epoch
    self.train_in_iter()
    │    └ <function Trainer.train_in_iter at 0x0000021BF6CD88C8>
    └ <yolox.core.vid_trainer.Trainer object at 0x0000021BECA84080>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\vid_trainer.py", line 131, in train_in_iter
    self.train_one_iter()
    │    └ <function Trainer.train_one_iter at 0x0000021BF6CD8950>
    └ <yolox.core.vid_trainer.Trainer object at 0x0000021BECA84080>

  File "c:\users\desktop\downloads\elston\yolov\yolox\core\vid_trainer.py", line 147, in train_one_iter
    outputs = self.model(inps, targets, lframe = self.exp.lframe,gframe = self.exp.gframe)
              │    │     │     │                 │    │   │               │    │   └ 16
              │    │     │     │                 │    │   │               │    └ ╒════════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
              │    │     │     │                 │    │   │               └ <yolox.core.vid_trainer.Trainer object at 0x0000021BECA84080>
              │    │     │     │                 │    │   └ 0
              │    │     │     │                 │    └ ╒════════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...
              │    │     │     │                 └ <yolox.core.vid_trainer.Trainer object at 0x0000021BECA84080>
              │    │     │     └ <unprintable Tensor object>
              │    │     └ <unprintable Tensor object>
              │    └ RTMDet(
              │        (backbone): CSPNeXt(
              │          (stem): Sequential(
              │            (0): ConvModule(
              │              (conv): Conv2d(3, 40, kernel_size=(3, 3...
              └ <yolox.core.vid_trainer.Trainer object at 0x0000021BECA84080>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {'lframe': 0, 'gframe': 16}
           │             └ <unprintable tuple object>
           └ <bound method RTMDet.forward of RTMDet(
               (backbone): CSPNeXt(
                 (stem): Sequential(
                   (0): ConvModule(
                     (conv):...

  File "c:\users\desktop\downloads\elston\yolov\yolox\models\rtmdet.py", line 28, in forward
    neck_out, targets, x, lframe=lframe,gframe=gframe
    │         │        │         │             └ 16
    │         │        │         └ 0
    │         │        └ <unprintable Tensor object>
    │         └ <unprintable Tensor object>
    └ <unprintable tuple object>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
           │             │        └ {'lframe': 0, 'gframe': 16}
           │             └ <unprintable tuple object>
           └ <bound method RTMDetHead.forward of RTMDetHead(
               (cls_convs): ModuleList(
                 (0): Sequential(
                   (0): BaseConv(
                     ...

  File "c:\users\desktop\downloads\elston\yolov\yolox\models\rtmdetHead.py", line 449, in forward
    conf_output = conf_output
                  └ None

  File "c:\users\desktop\downloads\elston\yolov\yolox\models\rtmdetHead.py", line 610, in get_losses
    torch.cuda.empty_cache()
    │     │    └ <function empty_cache at 0x0000021BBCD74D08>
    │     └ <module 'torch.cuda' from 'C:\\Users\\Desktop\\anaconda3\\envs\\yolov\\lib\\site-packages\\torch\\cuda\\__init__.py'>
    └ <module 'torch' from 'C:\\Users\\Desktop\\anaconda3\\envs\\yolov\\lib\\site-packages\\torch\\__init__.py'>

  File "C:\Users\Desktop\anaconda3\envs\yolov\lib\site-packages\torch\cuda\memory.py", line 121, in empty_cache
    torch._C._cuda_emptyCache()
    │     │  └ <built-in function _cuda_emptyCache>
    │     └ <module 'torch._C' from 'C:\\Users\\Desktop\\anaconda3\\envs\\yolov\\lib\\site-packages\\torch\\_C.pyd'>
    └ <module 'torch' from 'C:\\Users\\Desktop\\anaconda3\\envs\\yolov\\lib\\site-packages\\torch\\__init__.py'>

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

您好，我想换 YOLOX 的 base detector 然后用 RTMDET instead. 我现在 backbone 把他换了， RTMDet 的 neck 也加进去了可是最大的问题是换 YOLOX 的 head。 
我现在的 features 进去 RTMDET 的 backbone 和 neck 之后就进去 RTMDET head 然后我把 cls_score, obj_score 跟 reg_score 拿了, 他们都有三个 tensor 在里面，就是三个不同的 scale, 跟 yolovp_msa.py 里面的 obj_output, cls_output and reg_output 换去 RTMDet 的，三个都一样 tensor shape.

这个方法您觉得对不对？我跑的时候有了一些上面的 errors，不知道如果你弄 FCOS 跟其他 YOLOX alternative 的时候有没有这一样的问题？

**Comment by YuHengsss** [comment]
`2024-12-18 17:29:54 | ERROR    | yolox.models.rtmdetHead:608 - OOM RuntimeError is raised due to the huge memory cost during label assignment.                            CPU mode is applied in this batch. If you want to avoid this issue,                            try to reduce the batch size or image size.`

I have met similar issues too. But they are caused by the incorrect lable assignment code. Please carefully check labels relative to the losses [here](https://github.com/YuHengsss/YOLOV/blob/5f069b29e201c4e099c7c3827cc6c63823ce3141/yolox/models/v_plus_head.py#L719).

**Comment by Elstuhn** [comment]
Alright, thanks for your guidance! Will experiment and check the losses for now and see how it goes

**Comment by Elstuhn** [comment]
你还记得怎么fix这个error吗？我弄了几天了还不能fix

**Comment by YuHengsss** [comment]
Hello, I could not tell exactly how this bug was fixed (casue it has been one year). 
I guess the reason comes from the label assignment strategy of RMTDET is different from the one used in YOLOX. For YOLOV head, you could simply use the [IoU](https://github.com/YuHengsss/YOLOV/blob/2c72a1fb143c91576e1fa067bc0d7dbde754f5de/yolox/models/yolovp_msa.py#L598) to refine this classification score. 
For V++ head, you may need to rewrite the [label assigment strategy](https://github.com/YuHengsss/YOLOV/blob/2c72a1fb143c91576e1fa067bc0d7dbde754f5de/yolox/models/v_plus_head.py#L480) accordingly based on the customed head. 

Could you try YOLOV head for this new detector? V++ head is a little bit complex for me to recall the details.

**Comment by Elstuhn** [comment]
Hey, thanks for your quick reply and your suggestion, I found the issue was with the RTMDet backbone to neck area where the neck was producing outputs of nan for some reason, I shall continue trying to see what is the problem and try to fix it
