### ISSUE TITLE
Building error: I tried to install yolov but got the following error!

### ISSUE THREAD

**Issue by senstar-hsoleimani** [YuHengsss/YOLOV#69]
pip install -r requirements.txt
Collecting numpy (from -r requirements.txt (line 1))
  Downloading numpy-1.26.2-cp311-cp311-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 61.2/61.2 kB 463.4 kB/s eta 0:00:00
Collecting torch>=1.7.0 (from -r requirements.txt (line 2))
  Downloading torch-2.1.1-cp311-cp311-win_amd64.whl.metadata (26 kB)
Collecting opencv_python (from -r requirements.txt (line 3))
  Downloading opencv_python-4.8.1.78-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting loguru (from -r requirements.txt (line 4))
  Downloading loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting scikit-image (from -r requirements.txt (line 5))
  Downloading scikit_image-0.22.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting tqdm (from -r requirements.txt (line 6))
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 57.6/57.6 kB 3.0 MB/s eta 0:00:00
Collecting torchvision>=0.10.0 (from -r requirements.txt (line 7))
  Downloading torchvision-0.16.1-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting Pillow (from -r requirements.txt (line 8))
  Downloading Pillow-10.1.0-cp311-cp311-win_amd64.whl.metadata (9.6 kB)
Collecting thop (from -r requirements.txt (line 9))
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Collecting ninja (from -r requirements.txt (line 10))
  Downloading ninja-1.11.1.1-py2.py3-none-win_amd64.whl.metadata (5.4 kB)
Collecting tabulate (from -r requirements.txt (line 11))
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting tensorboard (from -r requirements.txt (line 12))
  Downloading tensorboard-2.15.1-py3-none-any.whl.metadata (1.7 kB)
Collecting lap (from -r requirements.txt (line 13))
  Downloading lap-0.4.0.tar.gz (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 6.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting motmetrics (from -r requirements.txt (line 14))
  Downloading motmetrics-1.4.0-py3-none-any.whl (161 kB)
     ---------------------------------------- 161.5/161.5 kB 9.5 MB/s eta 0:00:00
Collecting filterpy (from -r requirements.txt (line 15))
  Downloading filterpy-1.4.5.zip (177 kB)
     ---------------------------------------- 178.0/178.0 kB 10.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting h5py (from -r requirements.txt (line 16))
  Downloading h5py-3.10.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
Collecting scikit-learn (from -r requirements.txt (line 17))
  Downloading scikit_learn-1.3.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting pycocotools>=2.0.2 (from -r requirements.txt (line 21))
  Downloading pycocotools-2.0.7-cp311-cp311-win_amd64.whl.metadata (1.1 kB)
Collecting onnx==1.8.1 (from -r requirements.txt (line 22))
  Downloading onnx-1.8.1.tar.gz (5.2 MB)
     ---------------------------------------- 5.2/5.2 MB 12.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "C:\Users\hossein.soleimani\Anaconda3\envs\yolov\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\hossein.soleimani\Anaconda3\envs\yolov\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hossein.soleimani\Anaconda3\envs\yolov\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hossein.soleimani\AppData\Local\Temp\pip-build-env-ici7uort\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hossein.soleimani\AppData\Local\Temp\pip-build-env-ici7uort\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\hossein.soleimani\AppData\Local\Temp\pip-build-env-ici7uort\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\hossein.soleimani\AppData\Local\Temp\pip-build-env-ici7uort\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 75, in <module>
      AssertionError: Could not find "cmake" executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by xjyisok** [comment]
I suggest that you first install torch torchvision from official website and use its' command of cuda(be care of your gpu version). Then install other packages one by one as the packages' version my not match each other,  your torch and torchvision may be cpu version if you install then by "pip install -r requirements.txt" instantly
