### ISSUE TITLE
Can you tell me how to solve this problem? I use a new model and pre trained weights yolov++to train my dataset

### ISSUE THREAD

**Issue by andynnnnn** [YuHengsss/YOLOV#81]
Traceback (most recent call last):

  File "D:/Github/YOLOV-master/YOLOV-master/tools\train.py", line 140, in <module>
    args=(exp, args),
          │    └ Namespace(batch_size=16, cache=False, ckpt='D:\\Github\\YOLOV-master\\YOLOV-master\\weights\\V++_FocalL.pth', devices=1, dist...
          └ ╒════════════════════╤═══════════════════════════════════════════════════════════════════════════════════════════════════════...

> File "D:\Github\YOLOV-master\YOLOV-master\yolox\core\launch.py", line 98, in launch
    main_func(*args)
    │          └ (╒════════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x0000014A201048B8>

  File "D:/Github/YOLOV-master/YOLOV-master/tools\train.py", line 117, in main
    trainer.train()
    │       └ <function Trainer.train at 0x0000014A27B1C798>
    └ <yolox.core.trainer.Trainer object at 0x0000014A28AB4F88>

  File "D:\Github\YOLOV-master\YOLOV-master\yolox\core\trainer.py", line 74, in train
    self.before_train()
    │    └ <function Trainer.before_train at 0x0000014A28AAE798>
    └ <yolox.core.trainer.Trainer object at 0x0000014A28AB4F88>

  File "D:\Github\YOLOV-master\YOLOV-master\yolox\core\trainer.py", line 175, in before_train
    batch_size=self.args.batch_size, is_distributed=self.is_distributed
               │    │    │                          │    └ False
               │    │    │                          └ <yolox.core.trainer.Trainer object at 0x0000014A28AB4F88>
               │    │    └ 16
               │    └ Namespace(batch_size=16, cache=False, ckpt='D:\\Github\\YOLOV-master\\YOLOV-master\\weights\\V++_FocalL.pth', devices=1, dist...
               └ <yolox.core.trainer.Trainer object at 0x0000014A28AB4F88>

TypeError: get_evaluator() got an unexpected keyword argument 'batch_size'

**Comment by YuHengsss** [comment]
If you want to train the model on your own dataset, here are steps:

1. **Train the yolox base detector**. In your case, you should modify the https://github.com/YuHengsss/YOLOV/blob/master/exps/swin_base/focal_large_base_vid.py and init the prertain weight using YOLOX_FocalLarge. However, this weight is not released yet. You may try YOLOX_SwinTiny with corresponding exp. Use the train.py in tools in this step to train the base detector.

2. **Train the V++ detector** with exps in https://github.com/YuHengsss/YOLOV/tree/master/exps/yolov%2B%2B and use the pretrain weight produced by step 1.  Use the vid_train.py in tools in this step to train the video detector.

**Comment by andynnnnn** [comment]
Thank you for your explanation; you've really helped me a lot！

**Comment by andynnnnn** [comment]
Hello again, I hope I'm not being too much of a bother. I've successfully run models through YOLOXS_VID and YOLOV_S on my own dataset, but I've noticed that the mAP50 on YOLOXS_VID is significantly higher than YOLOV_S (approximately 4 points higher). What should I do to improve the performance of YOLOV_S? Or should I consider trying a model with a larger parameter count?

**Comment by YuHengsss** [comment]
May I take a look at your training log on  yolox and yolov please?


---- Replied Message ----
From  ***@***.***> Date  06/06/2024 16:21 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [YuHengsss/YOLOV] Can you tell me how to solve this problem? I use a new model and pre trained weights yolov++to train my dataset (Issue #81)  

Reopened #81.

**Comment by multi-type** [comment]
@YuHengsss How did you obtain YOLOX-Swin Pretain Models on ImageNet VID? Please teach me.

**Comment by YangBo0411** [comment]
> May I take a look at your training log on yolox and yolov please?
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 06/06/2024 16:21 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [YuHengsss/YOLOV] Can you tell me how to solve this problem? I use a new model and pre trained weights yolov++to train my dataset (Issue #81) Reopened #81. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I got the same result, the mAP0.50:0.95 on YOLOXS_VID is significantly higher than YOLOV_S (approximately 4-5 points higher). Moreover, I tried to train models of other scales, such as yolox_l-yolov_l, yolox_x-yolov_x, swin_tiny_vid-v++_SwinTiny_decoupleReg,and got the same result.  My target is small object with approximately 10 * 10 pixels. Here is the training log of the  yolox_s model. How can I improve the performance of my yolov_s model?
[yolox_s_train_log.txt](https://github.com/user-attachments/files/18234989/yolox_s_train_log.txt)
[yolov_s_train_log.txt](https://github.com/user-attachments/files/18234990/yolov_s_train_log.txt)
